### ISSUE TITLE
High Trek Fixes

### ISSUE THREAD

**Issue by abbylarner** [eschilb/tiy_assignments#1]
- make your header shorter.  right now it is very tall and taking over most of my screen not allowing me to see the main content of the article
- center your content before your first breakpoint.  right now it is stuck to the left side of the screen.  you either need to center the content or make it full width
- make your entire feature article and social links clickable (right now only the text is linking)

**Comment by eschilb** [comment]
I shortened the header but was unsure how much was appropriate so that enough of the main content shows below.
Centered the content on screen before the breakpoint.
Made link areas clickable.
